Nama : Credenda Mirandantons

## NO .1

In [ ]:
list_plat_mobil = ['B 1234 AB' , 'B 6721 TY'  , 'B 1233 AY', 
                   'B 6629 DD' , 'B 1111 AM'  , 'B 6726 D' , 
                   'D 11223 KJ', 'AE 44677 GH', 'AE 67269 AA']

plat  = 'B 1234 AB'
nomor = plat.split()[1]
nomor = int(nomor)

genap  = 0 #inisialisasi awal
ganjil = 0

for s in list_plat_mobil : #Definite Iteration
    nomor = int(s.split()[1])

    # 2 kondisi
    if nomor%2 == 0 :
        genap = genap + 1
    else :
        ganjil = ganjil + 1  

#hasil
print("Jumlah plah ganjil = ", ganjil)
print('Jumlah plat genap  = ', genap)

Jumlah plah ganjil =  7
Jumlah plat genap  =  2

## NO .2

In [ ]:
x       = 2  # variabel inisiasi
y       = 3  # variabel inisiasi
length  = 12 # panjajng deret
count   = 0


list_fibonacci = [x, y]
for s in range(length - 2):
    maka = x + y
    x = y
    y = maka
    list_fibonacci.append(maka)

print(list_fibonacci)

[2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377]


## NO .3

In [ ]:
# syarat : 1. Tidak boleh hanya memiliki 1 jenis category dalam 1 bundling
#          2. 1 Bundling boleh memiliki 2 category yang sama
#          3. Urutan tidak menjadi faktor pembeda (c1 - c2 - c3 = c2 - c1 - c3)

list_id_category = ['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7' , 'c8', 'c9', 'c10']
bundling_list    = []

# Nested For 
for x in list_id_category :
    category1 = x #categori pertama
    for y in list_id_category:
        category2 = y #category kedua
        for z in list_id_category :
            category3 = z
            temporary =  sorted([category1, category2, category3])
            if temporary not in bundling_list and category1!=category2!=category3:
                bundling_list.append(temporary)
        


print(len(bundling_list))

210

## NO .4

In [ ]:
def sam(metode, a):
    metode = metode.lower() # huruf pada metode dibuat kecil semua
    if metode == 'first_char':
        hasil = a[0]  # mengambil huruf pertama pada kata
        return hasil
    elif metode == 'last_char':
        hasil = a[-1] # mengambil huruf terahkir pada kata
        return hasil
    elif metode == 'num_chars':
        hasil = len(a) # menghitung panjang hurhuf pada kata
        return hasil
    elif metode == 'num_vowels': # menghitung panjang hurhuf vokal pada kata
        huruf_vokal = {'a': 0,
                       'i': 0,
                       'u': 0,
                       'e': 0, 
                       'o': 0}
        total_huruf_vokal = 0
        for karakter in a:
            if karakter in ['a', 'i', 'u', 'e',  'o']:
                huruf_vokal[karakter] += 1
                total_huruf_vokal += 1
        print(f'Total huruf vokal: {total_huruf_vokal}')
        print(f"""\
          a -> {huruf_vokal['a']}
          i -> {huruf_vokal['i']}
          u -> {huruf_vokal['u']}
          e -> {huruf_vokal['e']}
          o -> {huruf_vokal['o']}\
          """)
    else :
        hasil = '-'

sam('num_vowels', 'memasak')

Total huruf vokal: 3
          a -> 2
          i -> 0
          u -> 0
          e -> 1
          o -> 0

## NO .5

In [ ]:
import pandas as pd

# Memanggil data
set = pd.read_csv('rakamin_store_city_monthly.csv', sep=';')

# Mengambil 'gmail'
email = 'izharhalim@gmail.com'
'gmail' in email

# Menambah kolom is_gmail
set['is_gmail'] = set['email'].apply(lambda x: 'gmail' in x)
set.head()

#Mengambil '2018'
month = '2018-01'
'2018' in month

# Menambah kolom tahun
set['year'] = set['month'].apply(lambda x: '2018' in x)
set.head()

# Filter based on year = 2018 dan gmail
set_filter = set[(set.is_gmail == True) & (set. year == True)]
set_filter.head()

# Total user 
jumlah_user = set_filter.user_id.count()

# Print hasil
print('Jumlah user pengguna gmail pada tahun 2018 adalah ', jumlah_user)

Jumlah user pengguna gmail pada tahun 2018 adalah  3

## NO .6

In [ ]:
# Mengambil data
data = pd.read_excel('superstore.xls')

# Mengetahui type data pada tabel
#data.info()

# Membuat kolom baru berisi tahun 
data['year'] = data['Order Date'].dt.year

# Mengambil kolom kolom tertentu
data[['year', 'Order Date', 'Order ID', 'Region', 'Sales', 'Profit']].head()

# Function 
def total_sales_profit(region, year): #default year 2017
    #filter data
    data_filter = data[(data.year == year) & (data.Region == region)]
    
    # get value sum sales and profit
    data_sales  = data_filter.Sales.sum()
    data_profit = data_filter.Profit.sum()
    
    return data_sales, data_profit

# Hasil dari Point 1
print('Total jumlah Sales pada South Region di Tahun 2016 adalah  :', round(total_sales_profit('South', 2016)[0], 2))
print('Total jumlah Profit pada South Region di Tahun 2016 adalah :', round(total_sales_profit('South', 2016)[1], 2))

# Hasil dari Point 2
print('Total jumlah Sales pada West Region di Tahun 2017 adalah   :', round(total_sales_profit('West', 2017)[0], 2))
print('Total jumlah Profit pada West Region di Tahun 2017 adalah  :', round(total_sales_profit('West', 2017)[1], 2))

## NO. 7

In [ ]:
# memanggil data
df = pd.read_excel('superstore.xls')

#Membuat kolom baru berisi tahun 
df['year'] = df['Order Date'].dt.year

# Mengetahui Batas akhir Tahun
df['year'].max()

#menghitung total order per tahun
df['year'].value_counts()

#persebaran order per region
df['Region'].value_counts()

# Filter
df_group_year = df.groupby(['year', 'Customer ID', 'Customer Name'])['Sales'].sum().reset_index()
df_group_year.head()

# Describe
df_groupby_desc = df_group_year.groupby(['year'])['Sales'].describe(percentiles =[.25, .5, .75, .9, .95]).reset_index()
df_groupby_desc

df_groupby_year = df_group_year.merge(df_groupby_desc[['year', 'mean', '25%', '50%', '75%']], on='year', how ='inner')
df_groupby_year.head()

# Function 
def segment(x):
    if x['Sales'] < x['50%']:
        segment = 'Low'
    elif x['Sales'] <= x['75%'] and x['Sales'] >= x['50%']:
        segment = 'Mid'
    else :
        segment = ' High'
    return segment

df_groupby_year['segment'] = df_groupby_year.apply(lambda x: segment(x), axis = 1)
df_groupby_year

df_groupby_year[(df_groupby_year.year == 2017)].groupby(['segment'])['Customer ID'].nunique()


## **FINISH NO 1 - 7**😀